---
- apt_repository: 
    repo: 'ppa:nginx/stable'
    state: present
    update_cache: yes

- apt: 
    name: "{{ item }}" 
    state: latest 
    update_cache: yes
  with_items:
    - nginx
    - vim
    - git
    - ntp

- file:
    dest: /var/cache/nginx
    state: directory
    owner: www-data

- template:
    src: nginx-lb.conf.j2
    dest: /etc/nginx/sites-available/lbs.conf
  notify:
    - restart nginx
    
- file:
    src: /etc/nginx/sites-available/lbs.conf
    dest: /etc/nginx/sites-enabled/lbs.conf
    state: link
  notify:
    - restart nginx

- file:
    dest: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - restart nginx


