---
# process handlers

- name: stop service group
  become_user: "root"
  supervisorctl: >
    name="{{ service_name }}:"
    state=stopped

- name: restart service group
  become_user: "root"
  supervisorctl: >
    name="{{ service_name }}:"
    state=restarted

- name: restart django app
  become_user: "root"
  supervisorctl: >
    name="{{ service_name }}:django"
    state=restarted

- name: restart celery worker
  become_user: "root"
  supervisorctl: >
    name="{{ service_name }}:celery"
    state=restarted
