---
- hosts: asterisk_new 
  vars:
    - aperez_password: '$1$fut7ts9v$Zcgf2hu2NyH/nNjbCxmJ91'
 
  tasks:
  - name: Add user aperez
    user:
      name=aperez
      password={{ aperez_password }}

  - name: Add user remote to sudoers
    lineinfile:
      "dest=/etc/sudoers
      regexp='^aperez ALL'
      line='aperez ALL=(ALL) NOPASSWD: ALL'
      state=present"

