---
- name: restart apache
  become_user: "root"
  service: name=apache2 state=restarted

- name: disable apache
  become_user: "root"
  service: name=apache2 state=stopped enabled=no

- name: enable apache
  become_user: "root"
  service: name=apache2 state=started enabled=yes
