---

- name: download phantomjs
  get_url: >
    url={{ phantomjs_package }}
    dest=/tmp/phantomjs.tar.bz2
    sha256sum={{ phantomjs_sha256 }}
  tags: phantomjs

- name: install phantomjs
  become_user: 'root'
  shell: "tar xf /tmp/phantomjs.tar.bz2 -C {{ phantomjs_prefix }}/bin/ --overwrite --wildcards '**/bin/phantomjs' --strip-components=2"
  tags: phantomjs
