---

- name: stop webapp
  become_user: "root"
  supervisorctl: >
    name="{{ service_name }}:"
    state=stopped
  tags:
    - stop_webapp

- name: start webapp
  become_user: "root"
  supervisorctl: >
    name="{{ service_name }}:"
    state=restarted
  tags:
    - start_webapp
