---

- name: create new database dump
  become: no
  #local_action: shell ssh {{ live_db_host }} "pg_dump -F t -O -U {{ live_db_user }} {{ live_db_name }} | gzip -c > {{ remote_tempfile }}"
  local_action: shell ssh {{ live_host_user }}@{{ live_db_host }} "pg_dump -Fc -f {{ remote_tempfile }} -O -U {{ live_db_user }} {{ live_db_name }}"
  tags:
    - create_dump
    - import_database

- name: download database dump
  become: no
  local_action: shell scp -q {{ live_host_user }}@{{ live_db_host }}:{{ remote_tempfile }} {{ local_tempfile }}
  tags:
    - download_dump
    - import_database

- name: copy database dump to remote
  copy: >
    src="{{ local_tempfile }}"
    dest="{{ target_tempfile }}"
  tags:
    - download_dump
    - import_database

- name: copy local itemsfile to remote
  copy: >
    src="{{ local_itemsfile }}"
    dest="{{ target_itemsfile }}"
  when: local_itemsfile is defined
  tags:
    - restore_dump
    - import_database

- name: generate items from database dump
  become: no
  command: pg_restore -l -f {{ target_itemsfile }} {{ target_tempfile }}
  when: local_itemsfile is undefined
  tags:
    - restore_dump
    - import_database

- name: restore database dump
  become: no
  command: pg_restore -O -h {{ db_host }} -U {{ db_user }} -d {{ db_name }} -L {{ target_itemsfile }} {{ target_tempfile }}
  tags:
    - restore_dump
    - import_database
