- hosts: kam
  tasks:
  - name: Add repo  
    command: rpm -ivh http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm
  - name: Install Packets
    yum: name={{ item }} state=present
    with_items:
    - zabbix-agent
    - net-snmp.x86_64
  - name: Configuration  
    lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='Server=127.0.0.1' line='Server=10.170.0.190'
    lineinfile: dest=/etc/snmp/snmpd.conf regexp='com2sec notConfigUser  default       public' line='com2sec notConfigUser  default       t3l1nt3l'
  - name: Enabled
    service: name={{ item }} enabled=yes  
    with_items:
    - zabbix-agent
    - snmpd
  - name: Start
    service: name={{ item }} state=started
    with_items:
    - zabbix-agent
    - snmpd 
